const crypto = require('crypto');
const { extractText, DocumentProcessingError } = require('../parsers');
const { extractResume, extractJobDescription } = require('../ai/extractors');
const { getCatalog } = require('../services/courseService');
const { analyzeDocuments, getAnalysis } = require('../services/analysisService');
const { persistAndCache, loadAnalysis } = require('../services/persistenceService');
function response(res, data) { return res.json({ success: true, data, requestId: crypto.randomUUID() }); }
async function uploadJd(req, res, next) { try { const text = await extractText(req.file.originalname, req.file.buffer); const jd = extractJobDescription(text); return response(res, { filename: req.file.originalname, job_title: jd.job_title, mandatory_requirements: jd.mandatory_requirements, preferred_requirements: jd.preferred_requirements, responsibilities: jd.responsibilities, raw_text_length: text.length }); } catch (error) { next(error); } }
async function uploadResume(req, res, next) { try { const text = await extractText(req.file.originalname, req.file.buffer); const resume = extractResume(text); return response(res, { filename: req.file.originalname, candidate: resume.candidate, skills_count: resume.skills.length, skills: resume.skills, total_experience_years: resume.total_experience_years, raw_text_length: text.length }); } catch (error) { next(error); } }
async function analyze(req, res, next) { try { if (!req.files?.jd_file?.[0] || !req.files?.resume_files?.length) { return res.status(400).json({ success: false, detail: { code: 'INVALID_RESUME', message: 'At least one resume file and one JD file must be provided.' } }); } const jd = req.files.jd_file[0]; const results = await Promise.all(req.files.resume_files.map(file => analyzeDocuments({ resumeFilename: file.originalname, resumeBytes: file.buffer, jdFilename: jd.originalname, jdBytes: jd.buffer }).then(persistAndCache))); results.sort((a, b) => b.overall_score - a.overall_score); if (results.length === 1) return response(res, results[0]); return response(res, { job_title: results[0].job_title, total_candidates: results.length, rankings: results.map((item, index) => ({ rank: index + 1, candidate_name: item.candidate.name, score: item.overall_score, decision: item.decision, analysis_id: item.analysis_id })), detailed_results: results }); } catch (error) { next(error); } }
async function findResult(id) { return getAnalysis(id) || loadAnalysis(id); }
async function getResult(req, res, next) { try { const result = await findResult(req.params.analysisId); if (!result) return res.status(404).json({ success: false, detail: { code: 'ANALYSIS_NOT_FOUND', message: `Analysis ID '${req.params.analysisId}' not found.` } }); return response(res, result); } catch (error) { next(error); } }
async function getReport(req, res, next) { try { const result = await findResult(req.params.analysisId); if (!result) return res.status(404).json({ success: false, detail: { code: 'ANALYSIS_NOT_FOUND', message: `Analysis ID '${req.params.analysisId}' not found.` } }); const report = `RESUME MATCH REPORT\n\nCandidate: ${result.candidate.name}\nPosition: ${result.job_title}\nMatch Score: ${result.overall_score}%\nDecision: ${result.decision}\n\nSkills: ${result.category_scores.skills}%\nExperience: ${result.category_scores.experience}%\nResponsibilities: ${result.category_scores.responsibilities}%\nEducation: ${result.category_scores.education}%\n\nMatched: ${result.matched_requirements.join(', ') || 'None'}\nPartial: ${result.partial_requirements.join(', ') || 'None'}\nMissing: ${result.missing_requirements.join(', ') || 'None'}\n\n${result.explanation}`; return response(res, { analysis_id: result.analysis_id, report }); } catch (error) { next(error); } }
function courses(req, res) { return response(res, { total_courses: getCatalog().length, courses: getCatalog() }); }
module.exports = { uploadJd, uploadResume, analyze, getResult, getReport, courses, DocumentProcessingError };
